# Generated by Django 2.2.5 on 2021-06-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='backAngCheck',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='question',
            name='dampCheck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='elbowCheck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rlAngCheck',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='question',
            name='rlTimeCheck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vibCheck',
            field=models.IntegerField(default=0),
        ),
    ]
